version: '3.8'
name: minecraft
services:
  server:
    image: ghcr.io/codecraft3r/packwiz-container:main
    environment:
      - GH_USERNAME=poiesis-ed
      - GH_REPO=minecraft
      - MB_RAM=6144
    volumes:
      - world-data:/mnt/server/world
      - /root/mc-globals/whitelist.json:/mnt/server/whitelist.json
    ports:
      - "25565:25565"
    restart: unless-stopped
  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: server
      RCON_PASSWORD: packwiz
      INITIAL_DELAY: 10m
    volumes:
      - world-data:/data:ro
      - /root/mc-backup:/backups

volumes:

  world-data:
