[metadata]
name = "photon_v1.2a.zip"
side = "client"
project_url = "https://modrinth.com/project/lLqFfGNs"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "lLqFfGNs"
version = "rz2vlXVm"
url = "https://cdn.modrinth.com/data/lLqFfGNs/versions/rz2vlXVm/photon_v1.2a.zip"

[download.hashes]
sha1 = "6ad7e57f22ceb5530b168d077414abc8387c9b04"
sha512 = "6dd3e8078c5a7958638259a3472ce1192e549e0683c5c668df25bfcff5d282af5fe791e423490561c4a2e68f3933f4ff2ef2ef689f13a4774bfdef86d7994db4"
