[metadata]
name = "Solas Shader V3.4.zip"
side = "client"
project_url = "https://modrinth.com/project/EpQFjzrQ"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "EpQFjzrQ"
version = "syqezVYV"
url = "https://cdn.modrinth.com/data/EpQFjzrQ/versions/syqezVYV/Solas%20Shader%20V3.4.zip"

[download.hashes]
sha1 = "370bfdf5de02aca727517050b407afc761767f35"
sha512 = "99300ad2b9fdd33162fff571b9df089b7b09189c050fc2da7c51c5c54780d024faa952c4083cbcb5596c115be09c8f9764d92afc61b13ad0919cfeeab6168b1f"
