#Configuration for all carts and cart-like vehicles, check log for automatic "pull_animals" list.
[carts]

	#The Supply Cart, a type of cart that stores items
	[carts.supply_cart]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4

	#The Animal Cart, a type of cart to haul other animals
	[carts.animal_cart]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4

	#The Plow, an animal pulled machine for tilling soil and creating paths
	[carts.plow]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4

	#The Hand Cart, a player pulled cart that stores items
	[carts.hand_cart]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = ["minecraft:player"]
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4

	#The Reaper, a cart that harvests crops
	[carts.reaper]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4

	#The Seed Drill, a cart that plants crops
	[carts.seed_drill]
		#Entity that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []
		#Slow speed modifier toggled by the sprint key
		# Default: -0.65
		# Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Base speed modifier applied to animals (-0.5 = half normal speed)
		# Default: 0.0
		# Range: -1.0 ~ 0.0
		pull_speed = 0.0
		#Damage needed to destroy the cart. Damage accumulates over time but decays at a rate of 2 damage per second.
		# Default: 4
		# Range: 1 ~ 100
		destroy_damage = 4
