[metadata]
name = "create-1.21.1-6.0.9.jar"
side = "both"
project_url = "https://modrinth.com/project/LNytGWDc"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "LNytGWDc"
version = "n7NADxiG"
url = "https://cdn.modrinth.com/data/LNytGWDc/versions/n7NADxiG/create-1.21.1-6.0.9.jar"

[download.hashes]
sha1 = "bf08bf8980c080f42d6f644f4f44a725cf7c3be9"
sha512 = "8b3b3d9b6874f31a538add81390dff26b5f9475da6349dc52fc20dbde802edfc32ead511e12291198591574d42605f916f1acbadc2437056eea615d8586bf7cf"
