[metadata]
name = "ferritecore-7.0.3-neoforge.jar"
side = "both"
project_url = "https://modrinth.com/project/uXXizFIs"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "uXXizFIs"
version = "x7kQWVju"
url = "https://cdn.modrinth.com/data/uXXizFIs/versions/x7kQWVju/ferritecore-7.0.3-neoforge.jar"

[download.hashes]
sha1 = "9563692efb708b6b568df27a01ec52f6311928ef"
sha512 = "19af89a2075bb10a63884fa853ebf84b02c79dc3242430ecdad056fd764fdcde367a7303276b329df01b0736e2ef264c5d80c7dc92c6aebd244f556a230bb417"
