[metadata]
name = "Jade-1.21.1-NeoForge-15.10.5.jar"
side = "both"
project_url = "https://modrinth.com/project/nvQzSEkH"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "nvQzSEkH"
version = "yd8FKCmx"
url = "https://cdn.modrinth.com/data/nvQzSEkH/versions/yd8FKCmx/Jade-1.21.1-NeoForge-15.10.5.jar"

[download.hashes]
sha1 = "d5bf134b3dbde9f5258666823900e21341dc0a50"
sha512 = "678b998677a3d73f98f82dac4093893bfc8a3c2335ec627b4147811c381a040475decdb8db31cc3cbe600abb5a7a6dedcd356eed0ba471af0becdcf49bf5b137"
