[metadata]
name = "lithium-neoforge-0.15.2+mc1.21.1.jar"
side = "both"
project_url = "https://modrinth.com/project/gvQqBUqZ"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "gvQqBUqZ"
version = "OLpCvF3o"
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/OLpCvF3o/lithium-neoforge-0.15.2%2Bmc1.21.1.jar"

[download.hashes]
sha1 = "54457ba68b0066a5b6034655f8d31a29a3e5e6b1"
sha512 = "86ed9b0d2d267f6dab87e49e0757341fccc8c3efe3b734a496d2b72eee06e903c0f4a6852ec14e30b69bf65885975d2d838f1add73d222c60a22c93f25a0cfb0"
