[metadata]
name = "rechiseledcreate-1.1.0-neoforge-mc1.21.jar"
side = "both"
project_url = "https://modrinth.com/project/E6867niZ"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "E6867niZ"
version = "TzPaH8MY"
url = "https://cdn.modrinth.com/data/E6867niZ/versions/TzPaH8MY/rechiseledcreate-1.1.0-neoforge-mc1.21.jar"

[download.hashes]
sha1 = "64f92a5e2f158935e4188bb3966a47aa15083e17"
sha512 = "f5ef2ed26e82adcdf403430f9d0ea57cbff616a7d964b9891eb0a06107f180e740c47284a44a4c8733fddc6d8f58637e71edee68ff853d938df0dbf2b7084fe0"
