[metadata]
name = "xaeroworldmap-neoforge-1.21.1-1.40.11.jar"
side = "both"
project_url = "https://modrinth.com/project/NcUtCpym"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "NcUtCpym"
version = "arbQPyvf"
url = "https://cdn.modrinth.com/data/NcUtCpym/versions/arbQPyvf/xaeroworldmap-neoforge-1.21.1-1.40.11.jar"

[download.hashes]
sha1 = "c6f596bb6bc7d734100b7dbc8a57f69a5fb549a3"
sha512 = "a4bb890dbac27937411f570432ebc5a4cc5df9562c22e7c3d6a6516ff303bfcb7f35fb39d2ce42a51591a4b2a5b5debfc933fda3f5a552560442fe69f8828b0b"
