# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Cache gopath
      uses: actions/cache@v4
      id: cache-gopath
      env:
        cache-name: gopath-cache
      with:
        path: $HOME/go
        key: ${{ runner.os }}-run-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-run-
          ${{ runner.os }}-
    
    - if: ${{ steps.cache-gopath.outputs.cache-hit != 'true' }}
      name: Install Packwiz
      continue-on-error: true
      run: go install github.com/packwiz/packwiz@latest
      
    - name: Export mrpack
      run: packwiz modrinth export --output "poiesis-${{ github.ref_name }}.mrpack"
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: poiesis-${{ github.ref_name }}.mrpack
      
      
      
        
      
    
